- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    
    resource_group_name: "Globant_demo_rg"
    location: "eastus"
    templateLink1: 'https://raw.githubusercontent.com/paddy6987/azure-quickstart-templates/master/dsc-extension-iis-server-windows-vm/azuredeploy.json' 
    #templateLink2: 'https://raw.githubusercontent.com/paddy6987/tower/master/key_vault.json'
    paramsLink: 'https://raw.githubusercontent.com/paddy6987/azure-quickstart-templates/master/dsc-extension-iis-server-windows-vm/azuredeploy.parameters.json'
   
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: '{{ resource_group_name }}'
        location: '{{ location }}'
        template_link: '{{ templateLink1 }}'
        parameters_link: '{{ paramsLink }}'
        
#  - name: Deploy vault ARM template
 #   azure_rm_deployment:
 #       state: present
 #       resource_group_name: '{{ resource_group_name }}'
 #       location: '{{ location }}'
 #       template_link: '{{ templateLink2 }}'     
        
        # parameters_link: '{{ paramsLink }}'

 
