- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
     resourceGroup: "Globant_vault_rg"
     location: "eastus"
     templateLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/key_vault.json' 
     
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: '{{ resourceGroup }}'
        location: '{{ location }}'
        template_link: '{{ templateLink }}'
        "parametersLink": {
          "uri":"https://raw.githubusercontent.com/paddy6987/tower/master/vault_parameter.json",
          "contentVersion":"1.0.0.0" }
