- name: CREATE KEY_VAULT ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    
    resourceGroup: "Globant_vault_rg"
    location: "eastus"
    templateLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/key_vault.json' 
    #paramsLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/vm_parameter.json'
   
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: '{{ resourceGroup }}'
        location: '{{ location }}'
        template_link: '{{ templateLink }}'
