- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  
  tasks:
  - name: Create Azure Deploy
    azure_rm_deployment:
      state: present
      resource_group_name: dev-ops-cle
      template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json'
      parameters:
        adminUsername:
        value: mytestacct1
        adminPassword:
        value: mytestpass1
        dnsNameForPublicIP:
        value: GEN-IP
