- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # Variables 'resgrp' and 'location' need to be provided at command line with arg --extra-vars or fom parameter.
    templateLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/vm.json' 
    paramsLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/VM_parameter.json'
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        parameters_link: '{{ paramsLink }}'
        resource_group_name: '{{ resgrp }}'
        # location seems to be not optional
        location: '{{ location }}'
        template_link: '{{ templateLink }}'
        
