- name: CREATE ARM Deployment PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    
    templateLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/vm.json' 
    #paramsLink: 'https://raw.githubusercontent.com/paddy6987/tower/master/vm_parameter.json'
   
   
  tasks:
  - name: Deploy ARM template
    azure_rm_deployment:
        state: present
        resource_group_name: "Globant_rg"
        location: "eastus"
        template_link: '{{ templateLink }}'
       # parameters_link: '{{ paramsLink }}'
        
